services:
  web:
    build:
      context: .
      target: dev   # usa la etapa "dev"
    ports:
      - "4321:4321"
    env_file:
      - .env
    networks:
      - astra-network
    volumes:
      # live-reload sin rebuild
      - .:/app
      - /app/node_modules
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
        - path: ./astro.config.mjs
          action: sync
          target: /app/astro.config.mjs
        - path: ./tailwind.config.mjs
          action: sync
          target: /app/tailwind.config.mjs
        - path: ./package.json
          action: rebuild

networks:
  astra-network:
    external: true